apiVersion: v2
name: postgresus
description: A Helm chart for Postgresus - PostgreSQL backup and management system
type: application
version: 0.0.0
appVersion: "latest"
keywords:
  - postgresql
  - backup
  - database
  - restore
home: https://github.com/RostislavDugin/postgresus

sources:
  - https://github.com/RostislavDugin/postgresus
  - https://github.com/RostislavDugin/postgresus/tree/main/deploy/helm

maintainers:
  - name: Rostislav Dugin
    url: https://github.com/RostislavDugin

icon: https://raw.githubusercontent.com/RostislavDugin/postgresus/main/frontend/public/logo.svg
